//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOPOKKI_APP.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateCheckIn { get; set; }
        public Nullable<System.DateTime> DateCheckOut { get; set; }
        public int TableID { get; set; }
        public int Status { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual TableFood TableFood { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
